export { default as Social } from './social/Social'
export { default as Header } from './header/Header'
export { default as Wst } from './wst/Wst'
export { default as Features } from './features/Features'
export { default as Demo } from './demo/Demo'
export { default as Blogs } from './blogs/Blogs'
export { default as Footer } from './footer/Footer'
